extends:
  - standard  # eslint-config-standard

plugins:
  - standard  # eslint-plugin-standard
  - promise   # eslint-plugin-promise
  - import    # eslint-plugin-import

settings:
  # eslint-import-resolver-webpack
  # webpackの設定からモジュールのパスを解決する
  # bowerを使用しないならば node (eslint-import-resolver-node) で良い
  import/resolver: webpack
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2

rules:
  import/no-unresolved: 2

env:
  browser: true
  mocha: true